// Generated by gencpp from file rospy_pkg/MsgTutorial.msg
// DO NOT EDIT!


#ifndef ROSPY_PKG_MESSAGE_MSGTUTORIAL_H
#define ROSPY_PKG_MESSAGE_MSGTUTORIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rospy_pkg
{
template <class ContainerAllocator>
struct MsgTutorial_
{
  typedef MsgTutorial_<ContainerAllocator> Type;

  MsgTutorial_()
    : stamp()
    , data(0)  {
    }
  MsgTutorial_(const ContainerAllocator& _alloc)
    : stamp(_alloc)
    , data(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _stamp_type;
  _stamp_type stamp;

   typedef int32_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::rospy_pkg::MsgTutorial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rospy_pkg::MsgTutorial_<ContainerAllocator> const> ConstPtr;

}; // struct MsgTutorial_

typedef ::rospy_pkg::MsgTutorial_<std::allocator<void> > MsgTutorial;

typedef boost::shared_ptr< ::rospy_pkg::MsgTutorial > MsgTutorialPtr;
typedef boost::shared_ptr< ::rospy_pkg::MsgTutorial const> MsgTutorialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rospy_pkg::MsgTutorial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rospy_pkg::MsgTutorial_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rospy_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rospy_pkg': ['/home/parallels/catkin_ws/src/rospy_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rospy_pkg::MsgTutorial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rospy_pkg::MsgTutorial_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rospy_pkg::MsgTutorial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rospy_pkg::MsgTutorial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rospy_pkg::MsgTutorial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rospy_pkg::MsgTutorial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rospy_pkg::MsgTutorial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "742805c18e04d6693e5cb7da56c45e09";
  }

  static const char* value(const ::rospy_pkg::MsgTutorial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x742805c18e04d669ULL;
  static const uint64_t static_value2 = 0x3e5cb7da56c45e09ULL;
};

template<class ContainerAllocator>
struct DataType< ::rospy_pkg::MsgTutorial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rospy_pkg/MsgTutorial";
  }

  static const char* value(const ::rospy_pkg::MsgTutorial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rospy_pkg::MsgTutorial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string stamp\n\
int32 data\n\
";
  }

  static const char* value(const ::rospy_pkg::MsgTutorial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rospy_pkg::MsgTutorial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgTutorial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rospy_pkg::MsgTutorial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rospy_pkg::MsgTutorial_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.stamp);
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPY_PKG_MESSAGE_MSGTUTORIAL_H
